services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: mareasdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025" # puerto SMTP
      - "8025:8025" # interfaz web
    container_name: mailhog
