services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: mareasdb
    ports:
      - "5435:5432"
    volumes:
      - mareas_db_data:/var/lib/postgresql/data
    networks:
      - sigma-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sigma-backend
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
      SMTP_HOST: mailhog
    depends_on:
      - db
    volumes:
      - ./backups:/app/backups
      - ./static:/app/static
      - ./uploads:/app/uploads
    command: >
      sh -c "npx prisma migrate deploy && node dist/src/main"
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.sigma-backend.rule=Host(`${API_DOMAIN}`)'
      - "traefik.http.routers.sigma-backend.entrypoints=websecure"
      - "traefik.http.routers.sigma-backend.tls=true"
      - "traefik.http.routers.sigma-backend.tls.certresolver=mytlschallenge"
      - "traefik.http.services.sigma-backend.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik"
    networks:
      - sigma-network
      - traefik

  mailhog:
    image: mailhog/mailhog
    restart: always
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      - sigma-network

networks:
  sigma-network:
    driver: bridge
  traefik:
    external: true

volumes:
  mareas_db_data:
